version: "3.9"

services:
  backend:
    image: artela-network/${DOCKER_REPO:-block-explorer}:${DOCKER_TAG:-latest}
    restart: always
    stop_grace_period: 5m
    container_name: "block-explorer"
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: ./envs/common-blockscout.env
        required: true
      - path: ../.env
        required: false
    volumes:
      - ./logs/:/app/logs/
    ports:
      - "4000:4000"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.4.0
